### ISSUE TITLE
Chrome not registering for pushes

### ISSUE THREAD

**Issue by trevorrjohn** [blimmer/ember-appboy#23]
Hey, using your addon everything is working fine in Firefox and Safari, however I am experiencing some issues with Chrome. It appears I am getting a 404 within the `service-worker.js` and am getting these errors in the console:

```javascript
appboy.registerAppboyPushMessages()
undefined
:4200/service-worker.js:1 A bad HTTP response code (404) was received when fetching the script.
:4200/service-worker.js:1 GET http://localhost:4200/service-worker.js net::ERR_INVALID_RESPONSE
```

Any thoughts on why this would be happening? This is happening both when I run locally and when I run it in production and it is fingerprinted.

**Comment by trevorrjohn** [comment]
Oops! I think I am still having an issue, but this description is not representative of the error. I am going to close this and open a new one.

**Comment by blimmer** [comment]
@trevorrjohn , let me know if there's anything you figure out that should go into this project's docs. I'm not using push notifications in my app, so there's like a lot of room for improvement on docs for push.

**Comment by trevorrjohn** [comment]
Will do, I am currently talking with appboy to figure out what is going on.
