### ISSUE TITLE
Update docs for testing

### ISSUE THREAD

**Issue by trevorrjohn** [blimmer/ember-appboy#24]
Missing a few things for the testing stub: 

```javascript
let appboyApi = {
  initialize() {},
  openSession() {},
  changeUser() {},
  logCustomEvent() {},
  ab: {
    InAppMessage: {
      ClickAction() {
      }
    }
  },
  display: {
    automaticallyShowNewInAppMessages() {},
    destroyFeed() {},
    showFeed() {},
    toggleFeed() {},
    showInAppMessage() {},
  },
};
```

**Comment by blimmer** [comment]
Thanks! Wanna take a stab at a PR?

https://github.com/blimmer/ember-appboy/blob/master/tests/dummy/snippets/testing.js

**Comment by trevorrjohn** [comment]
Ah I was looking for that. Will update in a few.

**Comment by blimmer** [comment]
No problem - this project is my first time using [ember-code-snippet](https://github.com/ef4/ember-code-snippet) too.
