### ISSUE TITLE
appboy.registerAppboyPushMessages()

### ISSUE THREAD

**Issue by trevorrjohn** [blimmer/ember-appboy#27]
Hey, so I started using this addon, and right now it is as advertised and just a simple wrapper. Is this what you want this addon to be? I would like some abstraction around the above `appboy.registerAppboyPushMessages()` because it currently needs the Apple push id. (This seems like an API design flaw on Appboys part). 

Basically the question is, should I add this abstraction here or inside my own repo?

**Comment by blimmer** [comment]
Hey @trevorrjohn - can you give me more of an idea of what you're looking to do? You mentioned "around the above" but I think you might have forgotten a link?

**Comment by trevorrjohn** [comment]
Yeah sorry, so right now the Appboy api for `registerAppboyPushMessages` takes `yesCallback`, `noCallback` and a `Safari push token`.

I wanted to abstract this into some type of promise where you would only need to call a method like:

```javascript
emberAppboy.registerPushMessages().then(accepted => {}, denied => {});
```

This would be rewriting the Appboy API to be more user friendly. I don't know if this is something you want to take on or not.

**Comment by blimmer** [comment]
Additionally, I totally agree with you that this is a strange API for appboy to expose. In my experience, they've been very open to feedback when I've opened issues on their [public github project](https://github.com/Appboy/appboy-web-sdk/issues).

**Comment by trevorrjohn** [comment]
Totally makes sense. I did open an issue with them about some of my
concerns and they said they will fix it in the next point release.

**Comment by blimmer** [comment]
What do you think about adding a set of utility functions that could be documented and imported for these kinds of promises? For instance:

```javascript
// addon/utils/promisified-methods.js

export function rsvpIsPushGranted(safariPushId) {
   ... logic ...
   ... returns a promise ...
}
```

that way, people can still use the normal appboy wrappers, but we provide convenience methods they can if use if they want.

**Comment by trevorrjohn** [comment]
Hmm, I like the idea of this. This is basically what I am doing in my own app at the moment. The way I designed the Api to work is via a service. 

```javascript
export default Ember.Service.extend({
  updateUser(userId) {
    appboy.changeUser(userId);
  },

  register() {
    if (!appboy.isPushSupported()) {
      return RSVP.reject(AppboyError.createNotSupported());
    }

    if (appboy.isPushBlocked()) {
      return RSVP.reject(AppboyError.createPermissionBlocked());
    }

    return new RSVP.Promise((resolve, reject) =>
        appboy.registerAppboyPushMessages(
          resolve.bind(this),
          reject.bind(this, AppboyError.createPermissionDenied()),
          ENV.appboy.applePushId
        )
    );
  },

  isGranted() {
    if (!appboy.isPushSupported()) {
      return RSVP.reject(false);
    }

    return new RSVP.Promise((resolve, reject) =>
      appboy.isPushGranted(
        resolve.bind(this),
        reject.bind(this),
        ENV.appboy.applePushId
      )
    );
  }
});
```

I think this makes sense such that users could just import the addons service and use it however they need to. 

Thoughts?

**Comment by blimmer** [comment]
Hey @trevorrjohn thanks for showing me the service you're using. Sorry it has taken so long for me to get back to you.

I don't think I want to go as far as exposing a service - use cases differ so much that I think it would be overboard for this library. Stuff like this I think could only introduce confusion:

```javascript
  updateUser(userId) {
    appboy.changeUser(userId);
  },
```

That said, I really like the idea of exposing RSVP promisified methods in place of the callbacks. I think creating the utility methods I [mentioned above](https://github.com/blimmer/ember-appboy/issues/27#issuecomment-251706001) should be our action item out of this.

I opened #29 to track this work.

Thanks!
