### ISSUE TITLE
Could not find module `ember-require-module`

### ISSUE THREAD

**Issue by giaset** [blimmer/ember-appboy#40]
Hi,

Just upgraded to v0.2.7 to fix the issue with minified CSS, and all my tests are now failing with:

> Error: Could not find module `ember-require-module` imported from `ember-appboy/instance-initializers/appboy`

How do I fix this? Thanks!

**Comment by blimmer** [comment]
Whoops, I messed something up - let me get this fixed for you.

**Comment by blimmer** [comment]
@giaset will you please bump to v0.2.8 and test it now?

**Comment by giaset** [comment]
Works, thanks!
